name: calculadora-plenaria
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - libffi=3.4.4
  - openssl=3.0.9
  - pip=23.1.2
  - python=3.11.3
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - docutils==0.20.1
      - idna==3.4
      - kivy==2.2.1
      - kivy-deps-angle==0.3.3
      - kivy-deps-glew==0.3.1
      - kivy-deps-sdl2==0.6.0
      - kivy-examples==2.2.1
      - kivy-garden==0.1.5
      - pillow==10.0.0
      - pygments==2.15.1
      - pypiwin32==223
      - pywin32==306
      - requests==2.31.0
      - urllib3==2.0.3
